version: '3'
services:
  app:
    image: "fqrmix/accounting-chat-manager-kotlin:latest"
    ports:
      - "8080:8080"
    environment:
      TELEGRAM_TOKEN: ""
      POSTGRES_URL: ""
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
