version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      TELEGRAM_TOKEN: ""
      POSTGRES_HOST: ""
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
      POSTGRES_DATABASE: ""
