version: '3'
services:
  chat-manager-app:
    image: "fqrmix/accounting-chat-manager-kotlin:latest"
    networks:
      - docker-private-network
    env_file:
      - .env
    environment:
      TZ: "Europe/Moscow"
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      POSTGRES_URL: "${POSTGRES_URL}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    command: ["java", "-jar", "app.jar"]

networks:
  docker-private-network:
    external: true
